USE MASTER
GO
-- ==================================
--  CREACION DE BD EN EL DIRECTORIO
-- ================================== 
CREATE DATABASE ALMACEN
GO

USE ALMACEN
GO
-- ==================================
--        CREACION DE TABLA EMPRESA
-- ================================== 

--MODIFICACIONES EN TABLE INV_EMPRESA
CREATE TABLE INV_EMPRESA(
	ID_EMPRESA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CODIGO AS ('EMP'+RIGHT ('00' + CONVERT(VARCHAR,ID_EMPRESA),(2))),
	RUC VARCHAR(11) NOT NULL,
	EMPRESA VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(256) NOT NULL,
	OBSERVACIONES VARCHAR(300) DEFAULT '-',
)
GO
SELECT*FROM INV_EMPRESA
GO

INSERT INTO INV_EMPRESA(
    RUC,
	EMPRESA,
	DIRECCION
)
VALUES
(
	'20332970411','PACÍFICO','AV. JUAN DE ARONA NRO. 830 - SAN ISIDRO'
),
(
	'20106897914','ENTEL PERÚ','AV. REPUBLICA DE COLOMBIA NRO. 791 (PISO 14 ESQ. CDRA 34 PASEO D L REPUBLICA) - SAN ISIDRO'
),
(
	'20341841357','LATAM','CAL. ARICA NRO. 628 (PISO 6) - MIRAFLORES'
),
(
	'20100017491','TELEFÓNICA','CAL. DEAN VALDIVIA NRO. 148 DPTO. 201 URB. JARDIN - SAN ISIDRO'
),
(
	'20574650187','INNOVA SCHOOLS','MZA. I LOTE. 03 A.H. SEÑOR DE LA PICOTA - HUAMANGA - AYACUCHO'
),
(
	'20100041953','RIMAC SEGUROS','CAL. EL PARQUE NRO. 149 INT. PIS2 URB. JARDIN -SAN ISIDRO'
),
(
	'20517905454','CENCOSUD','CAL. AUGUSTO ANGULO NRO. 130 URB. SAN ANTONIO'
),
(
	'20563617072','OYP','PQ. 56 NRO. 18 C.H. TALARA'
),
(
	'20600093836','CULQUI','AV. METROPOLITANA MZA. B1 LOTE. 50 URB. CERES 2DA ETAPA'
),
(
	'20467534026','CLARO','AV. NICOLAS ARRIOLA NRO. 480 URB. SANTA CATALINA'
);
GO

-- ==================================
--        PROCEDURES ENTIDAD EMPRESA
-- ==================================

--PROCEDIMIENTO ALMACENADO BUSCAR EMPRESA
CREATE PROC USP_BUSCAREMPRESA
@BUSCAR NVARCHAR(100)
AS
SELECT * FROM INV_EMPRESA
WHERE EMPRESA LIKE @BUSCAR + '%'
GO

--PROCEDIMIENTO ALMACENADO EDITAR EMPRESA
CREATE PROC USP_EDITAREMPRESA
@ID_EMPRESA INT,
@RUC NVARCHAR(11),
@EMPRESA NVARCHAR(100),
@DIRECCION NVARCHAR(256),
@OBSERVACIONES NVARCHAR(300)
AS
UPDATE INV_EMPRESA SET RUC = @RUC, EMPRESA = @EMPRESA, DIRECCION = @DIRECCION, OBSERVACIONES = @OBSERVACIONES
WHERE ID_EMPRESA = @ID_EMPRESA
GO

--PROCEDIMIENTO ALMACENADO INSERTAR EMPRESA
CREATE PROC USP_INSERTAREMPRESA
@RUC NVARCHAR(11),
@EMPRESA NVARCHAR(100),
@DIRECCION NVARCHAR(256),
@OBSERVACIONES NVARCHAR(300)
AS
BEGIN
INSERT INTO INV_EMPRESA (
	RUC,
	EMPRESA,
	DIRECCION,
	OBSERVACIONES
)
VALUES (
	@RUC,
	@EMPRESA,
	@DIRECCION,
	@OBSERVACIONES
)
END
GO

--PROCEDIMIENTO ALMACENADO ELIMINAR EMPRESA
CREATE PROC USP_ELIMINAREMPRESA
@ID_EMPRESA INT
AS
DELETE INV_EMPRESA
WHERE ID_EMPRESA = @ID_EMPRESA
GO
-- ==================================
--        CREACION DE TABLA ALMACEN
-- ================================== 

--MODIFICACIONES EN TABLE INV_ALMACEN
CREATE TABLE INV_ALMACEN(
	ID_ALMACEN INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CODIGO AS ('ALM'+RIGHT ('00' + CONVERT(VARCHAR,ID_ALMACEN),(2))),
	NOMBRE_ALMACEN VARCHAR(60) NOT NULL,
	UBICACION VARCHAR(256) NOT NULL,
	DIRECCION VARCHAR(256) NOT NULL,
	CAPACIDAD INT NOT NULL,
	OBSERVACIONES VARCHAR(300) DEFAULT '-',
)
GO

SELECT*FROM INV_ALMACEN
GO

INSERT INTO INV_ALMACEN(
    NOMBRE_ALMACEN,
	UBICACION,
	DIRECCION,
	CAPACIDAD
)
VALUES
(
	'ALMACEN_1','1erNIVEL_A','AV. JUAN DE ARONA NRO. 830 - SAN ISIDRO','100'
),

(
	'ALMACEN_2','1erNIVEL_B','AV. NICOLAS ARRIOLA NRO. 480 URB. SANTA CATALINA','150'
);
GO
-- ==================================
--        CPROCEDURES ENTIDAD ALMACEN
-- ==================================

--PROCEDIMIENTO ALMACENADO BUSCAR ALMACEN
CREATE PROC USP_BUSCARALMACEN
@BUSCAR NVARCHAR(100)
AS
SELECT * FROM INV_ALMACEN
WHERE NOMBRE_ALMACEN LIKE @BUSCAR + '%'
GO

--PROCEDIMIENTO ALMACENADO EDITAR ALMACEN
CREATE PROC USP_EDITARALMACEN
@ID_ALMACEN INT,
@NOMBRE_ALMACEN NVARCHAR(100),
@UBICACION NVARCHAR(50),
@DIRECCION NVARCHAR(256),
@CAPACIDAD INT,
@OBSERVACIONES NVARCHAR(300)
AS
UPDATE INV_ALMACEN SET NOMBRE_ALMACEN = @NOMBRE_ALMACEN, UBICACION = @UBICACION, DIRECCION = @DIRECCION,CAPACIDAD =@CAPACIDAD, OBSERVACIONES = @OBSERVACIONES
WHERE ID_ALMACEN = @ID_ALMACEN
GO

--PROCEDIMIENTO ALMACENADO INSERTAR ALMACEN
CREATE PROC USP_INSERTARALMACEN
@NOMBRE_ALMACEN NVARCHAR(100),
@UBICACION NVARCHAR(50),
@DIRECCION NVARCHAR(256),
@CAPACIDAD INT,
@OBSERVACIONES NVARCHAR(300)
AS
BEGIN
INSERT INTO INV_ALMACEN (
	NOMBRE_ALMACEN,
	UBICACION,
	DIRECCION,
	CAPACIDAD
)
VALUES (
	@NOMBRE_ALMACEN,
	@UBICACION,
	@DIRECCION,
	@CAPACIDAD
)
END
GO

--PROCEDIMIENTO ALMACENADO ELIMINAR ALMACEN
CREATE PROC USP_ELIMINARALMACEN
@ID_ALMACEN INT
AS
DELETE INV_ALMACEN
WHERE ID_ALMACEN = @ID_ALMACEN
GO
-- ==================================
--        CREACION DE TABLA PRODUCTO
-- ================================== 

--MODIFICACIONES EN TABLE INV_ALMACEN
CREATE TABLE INV_PRODUCTO(
	ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CODIGO AS ('PROD'+RIGHT ('00' + CONVERT(VARCHAR,ID_PRODUCTO),(2))),
	NOMBRE_PRODUCTO VARCHAR(60) NOT NULL,
	ORIGEN VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(30) NOT NULL,
	EMPAQUE VARCHAR(30) NOT NULL,
	ABREVIATURA VARCHAR(10) NOT NULL,
	OBSERVACIONES VARCHAR(300) DEFAULT '-',
)
GO

SELECT*FROM INV_PRODUCTO
GO

INSERT INTO INV_PRODUCTO(
    NOMBRE_PRODUCTO,
	ORIGEN,
	ESTADO,
	EMPAQUE,
	ABREVIATURA,
	OBSERVACIONES
)
VALUES
(
	'APRODUCTO','CHINA','NUEVO','CAJA X 100 UN','APRCHICAJ','-'
),

(
	'BPRODUCTO','TAIWAN','NUEVO','CAJA X 20 UN','APRTAICAJ','-'
);
GO
-- ==================================
--        CPROCEDURES ENTIDAD PRODUCTOS
-- ==================================

--PROCEDIMIENTO ALMACENADO BUSCAR PRODUCTO
CREATE PROC USP_BUSCARPRODUCTO
@BUSCAR NVARCHAR(100)
AS
SELECT * FROM INV_PRODUCTO
WHERE NOMBRE_PRODUCTO LIKE @BUSCAR + '%'
GO

--PROCEDIMIENTO ALMACENADO EDITAR ALMACEN
CREATE PROC USP_EDITARPRODUCTO
@ID_PRODUCTO INT,
@NOMBRE_PRODUCTO VARCHAR(60),
@ORIGEN VARCHAR(30),
@ESTADO VARCHAR(30),
@EMPAQUE VARCHAR(30),
@ABREVIATURA VARCHAR(10),
@OBSERVACIONES VARCHAR(300)
AS
UPDATE INV_PRODUCTO SET NOMBRE_PRODUCTO = @NOMBRE_PRODUCTO, ORIGEN = @ORIGEN, ESTADO = @ESTADO,EMPAQUE = @EMPAQUE, ABREVIATURA = @ABREVIATURA, OBSERVACIONES = @OBSERVACIONES
WHERE ID_PRODUCTO = @ID_PRODUCTO
GO

--PROCEDIMIENTO ALMACENADO INSERTAR ALMACEN
CREATE PROC USP_INSERTARPRODUCTO
@NOMBRE_PRODUCTO NVARCHAR(60),
@ORIGEN VARCHAR(30),
@ESTADO VARCHAR(30),
@EMPAQUE VARCHAR(30),
@ABREVIATURA VARCHAR(10),
@OBSERVACIONES VARCHAR(300)
AS
BEGIN
INSERT INTO INV_PRODUCTO (
	NOMBRE_PRODUCTO,
	ORIGEN,
	ESTADO,
	EMPAQUE,
	ABREVIATURA,
	OBSERVACIONES
)
VALUES (
	@NOMBRE_PRODUCTO,
	@ORIGEN,
	@ESTADO,
	@EMPAQUE,
	@ABREVIATURA,
	@OBSERVACIONES
)
END
GO

--PROCEDIMIENTO ALMACENADO ELIMINAR ALMACEN
CREATE PROC USP_ELIMINARPRODUCTO
@ID_PRODUCTO INT
AS
DELETE INV_PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO
GO

-- ==================================
--        CREACION DE TABLA USUARIOS
-- ================================== 
CREATE TABLE INV_USUARIOS(
ID_USUARIO int identity(1,1) primary key,
NOMBRE nvarchar(100) not null,
CARGO nvarchar(100) not null,
LOGIN_USUARIO nvarchar(100) UNIQUE not null,
CLAVE_USUARIO nvarchar(100) not null,
)

INSERT INTO INV_USUARIOS VALUES ('admin','administrador','admin','cibertec123')
INSERT INTO INV_USUARIOS VALUES ('user','usuario','user','cibertec123')
INSERT INTO INV_USUARIOS VALUES ('jeffrey','administrador','jeffrey01','123')
INSERT INTO INV_USUARIOS VALUES ('luis','administrador','luis01','123')
INSERT INTO INV_USUARIOS VALUES ('alexandra','administrador','alexandra01','123')
INSERT INTO INV_USUARIOS VALUES ('bryan','administrador','bryan01','123')
INSERT INTO INV_USUARIOS VALUES ('camila','administrador','camila01','123')

-- ==================================
--        CREACION DE TABLA MOVIMIENTO
-- ================================== 

--MODIFICACIONES EN TABLE INV_ALMACEN
CREATE TABLE INV_MOVIMIENTO(
	ID_MOVIMIENTO int identity(1,1) primary key,
	ID_ALMACEN INT,
	ID_PRODUCTO INT,
	ID_USUARIO INT,
	ID_EMPRESA INT,
	CANTIDAD INT,
	GUIA_TRANSP VARCHAR(40) NOT NULL,
	OBSERVACIONES VARCHAR(300) DEFAULT '-',

	CONSTRAINT "FK_MOVIMIENTO_ALMACEN" FOREIGN KEY 
	(
		"ID_ALMACEN"
	) REFERENCES "dbo"."INV_ALMACEN" (
		"ID_ALMACEN"
	),
	CONSTRAINT "FK_MOVIMIENTO_PRODUCTO" FOREIGN KEY 
	(
		"ID_PRODUCTO"
	) REFERENCES "dbo"."INV_PRODUCTO" (
		"ID_PRODUCTO"
	),
	CONSTRAINT "FK_MOVIMIENTO_USUARIO" FOREIGN KEY 
	(
		"ID_USUARIO"
	) REFERENCES "dbo"."INV_USUARIOS" (
		"ID_USUARIO"
	),
	CONSTRAINT "FK_MOVIMIENTO_EMPRESA" FOREIGN KEY 
	(
		"ID_EMPRESA"
	) REFERENCES "dbo"."INV_EMPRESA" (
		"ID_EMPRESA"
	)
)
GO
SELECT*FROM INV_MOVIMIENTO
GO
